name: Continuous Integration

on:
  push:
    branches: [main]
    paths: ["**.zig"]

  pull_request:
    branches: [main]
    paths: ["**.zig"]

  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run example
        run: zig build example

  example_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run example test
        run: zig build example_test

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Generate coverage
        run: zig build cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: kcov-output
          fail_ci_if_error: true
          verbose: true

  lints:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run lints
        run: zig build lints
