name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Run `example` step
        run: zig build example

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Run `fmt` step
        run: zig build fmt
